window.CodeGenerator = (() => {
  const LANGUAGES = {
    batch: {
      name: "Batch",
      extension: "bat",
      comment: "::",
    },
    powershell: {
      name: "PowerShell",
      extension: "ps1",
      comment: "#",
    },
    bash: {
      name: "Bash",
      extension: "sh",
      comment: "#",
    },
    zsh: {
      name: "Zsh",
      extension: "zsh",
      comment: "#",
    },
  };

  function shellQuote(value) {
    return `'${String(value).replace(/'/g, "'\"'\"'")}'`;
  }

  function powershellQuote(value) {
    return `'${String(value).replace(/'/g, "''")}'`;
  }

  function batchQuote(value) {
    return `"${String(value).replace(/%/g, "%%").replace(/"/g, '""')}"`;
  }

  function getPath(parent, name, separator) {
    return parent ? `${parent}${separator}${name}` : name;
  }

  function generateBatch(nodes, root) {
    const out = [
      "@echo off",
      "setlocal",
      "",
      ":: Generated by Aifolix",
      `:: Root: ${root}`,
      "",
      `mkdir ${batchQuote(root)}`,
      `cd /d ${batchQuote(root)}`,
      "",
    ];

    const stack = [{ depth: 0, path: "" }];

    for (let i = 1; i < nodes.length; i++) {
      const node = nodes[i];

      while (stack.length && stack[stack.length - 1].depth >= node.depth) {
        stack.pop();
      }

      const parent = stack.length ? stack[stack.length - 1].path : "";
      const currentPath = getPath(parent, node.name, "\\");

      if (StructureParser.isFile(node.name)) {
        out.push(`:: Create file: ${currentPath}`);
        out.push(`type nul > ${batchQuote(currentPath)}`);
      } else {
        out.push(`:: Create folder: ${currentPath}`);
        out.push(`mkdir ${batchQuote(currentPath)}`);
        stack.push({ depth: node.depth, path: currentPath });
      }

      out.push("");
    }

    out.push(
      "echo.",
      "echo ========================================",
      "echo Folder structure created successfully!",
      "echo ========================================",
      "echo.",
      "tree /F",
      "",
      "endlocal",
    );

    return out.join("\n");
  }

  function generatePowerShell(nodes, root) {
    const out = [
      "# Generated by Aifolix",
      `# Root: ${root}`,
      "",
      `$root = ${powershellQuote(root)}`,
      "New-Item -ItemType Directory -Path $root -Force | Out-Null",
      "Set-Location -Path $root",
      "",
    ];

    const stack = [{ depth: 0, path: "" }];

    for (let i = 1; i < nodes.length; i++) {
      const node = nodes[i];

      while (stack.length && stack[stack.length - 1].depth >= node.depth) {
        stack.pop();
      }

      const parent = stack.length ? stack[stack.length - 1].path : "";
      const currentPath = getPath(parent, node.name, "\\");

      if (StructureParser.isFile(node.name)) {
        out.push(`# Create file: ${currentPath}`);
        out.push(`New-Item -ItemType File -Path ${powershellQuote(currentPath)} -Force | Out-Null`);
      } else {
        out.push(`# Create folder: ${currentPath}`);
        out.push(`New-Item -ItemType Directory -Path ${powershellQuote(currentPath)} -Force | Out-Null`);
        stack.push({ depth: node.depth, path: currentPath });
      }

      out.push("");
    }

    out.push(
      'Write-Host ""',
      'Write-Host "========================================"',
      'Write-Host "Folder structure created successfully!"',
      'Write-Host "========================================"',
      'Write-Host ""',
      "Get-ChildItem -Recurse",
    );

    return out.join("\n");
  }

  function generatePosix(nodes, root, shellName) {
    const out = [
      `#!/usr/bin/env ${shellName}`,
      "",
      "# Generated by Aifolix",
      `# Root: ${root}`,
      "",
      `root=${shellQuote(root)}`,
      'mkdir -p "$root"',
      'cd "$root" || exit 1',
      "",
    ];

    const stack = [{ depth: 0, path: "" }];

    for (let i = 1; i < nodes.length; i++) {
      const node = nodes[i];

      while (stack.length && stack[stack.length - 1].depth >= node.depth) {
        stack.pop();
      }

      const parent = stack.length ? stack[stack.length - 1].path : "";
      const currentPath = getPath(parent, node.name, "/");
      const quotedPath = shellQuote(currentPath);

      if (StructureParser.isFile(node.name)) {
        out.push(`# Create file: ${currentPath}`);
        out.push(`touch ${quotedPath}`);
      } else {
        out.push(`# Create folder: ${currentPath}`);
        out.push(`mkdir -p ${quotedPath}`);
        stack.push({ depth: node.depth, path: currentPath });
      }

      out.push("");
    }

    out.push(
      'echo ""',
      'echo "========================================"',
      'echo "Folder structure created successfully!"',
      'echo "========================================"',
      'echo ""',
      "find . -print",
    );

    return out.join("\n");
  }

  function generate(nodes, language = "batch") {
    if (!nodes.length) {
      const empty = {
        batch: "@echo off\n\necho No structure detected.",
        powershell: 'Write-Host "No structure detected."',
        bash: 'echo "No structure detected."',
        zsh: 'echo "No structure detected."',
      };
      return empty[language] || empty.batch;
    }

    const root = nodes[0].name;

    switch (language) {
      case "powershell":
        return generatePowerShell(nodes, root);
      case "bash":
        return generatePosix(nodes, root, "bash");
      case "zsh":
        return generatePosix(nodes, root, "zsh");
      case "batch":
      default:
        return generateBatch(nodes, root);
    }
  }

  function getLanguage(language) {
    return LANGUAGES[language] || LANGUAGES.batch;
  }

  return { generate, getLanguage, LANGUAGES };
})();
